### ISSUE TITLE
Slow to load with Safari

### ISSUE THREAD

**Issue by mrtankjump** [Color-Of-Code/dokuwiki-plugin-bpmnio#7]
Any page with a diagram rendering takes ~12 seconds to load in Safari (OS X). Using Safari's timeline recording, it looks all of that time is spent in JQuery.ready, triggered by DOM Content Loaded Event Dispatched.
I've tested on IE, FF, and Chrome and they all load pages with diagrams as fast as any other page.
I can send additional information if you are interested in checking it out, though at this point I'm just going to use another browser

**Comment by jdehaan** [comment]
Unfortunately I have no way to check this issue, I have no OS X. The bpmnio javascript is making use of DOM manipulations and SVG. Maybe the version you were using had trouble with that. In the meanwhile - sorry for the slow response time - did you maybe have a chance to retry it with a newer Safari version? Which version of Safari are you using?

Thanks for the background information. the ready() event is triggered by the browser after loading and in that callback a lot (actually probably all) operations are being performed. This unfortunately does not help too much to localize the source of the issue. Do you maybe observe some flickering? This could be a clue to intensive redraw or content lay-outing.

**Comment by jdehaan** [comment]
@mrtankjump I know there have been ages passing by. I update the bpmn-js to a newer release maybe that helps.

There have been a bunch of fixes since then https://github.com/bpmn-io/bpmn-js/issues?q=is%3Aissue+safari+is%3Aclosed and the javascript transpiling and browser compatibility layers also improved, so I hope this problem has gone.

Unfortunately this was nothing that I can directly control, debug or verify.
